### ISSUE TITLE
Location mappings block campaign-content folder in .NET

### ISSUE THREAD

**Issue by erikssonorjan** [sdl/dxa-flexible-campaign-content#1]
If you have a situation where there is no publication for an empty location, you can't access the "campaign-content" folder. DXA can't find the location and therefore shows an error message instead of letting MVC serving the static files.

You should be able to access the campaign files, regardless of the localization configuration for the current implementation, in the same way media files are served and stored in the BinaryData folder.

**Comment by NiclasCedermalm** [comment]
Yes, indeed that is a scenario I have not considered during the development of first version. In next version I have plans to introduce an HTTP module that manage the campaign assets instead of going directly to the unzipped campaign assets.

**Comment by NiclasCedermalm** [comment]
Corrected in Instant Campaign v1.1
