### ISSUE TITLE
Is this supported on SDL Web 8.6?

### ISSUE THREAD

**Issue by TimAlonso** [sdl/dxa-flexible-campaign-content#17]
The technical requirement stated [here](https://appstore.sdl.com/web-content-management/app/instant-campaign/748/) are: SDL Web 8.1.1/8.5 and DXA Java/.NET 1.7

I'm using working with SDL Cloud (Build 8.6) and wanted to confirm that this extension support this build version?

**Comment by NiclasCedermalm** [comment]
Hi, 
The event system extension (which handle uploads of campaigns into Tridion) has been compiled against SDL Web 8.5 DLLs. I think it will work against 8.6 as well, but that is nothing I've verified. Let me know if it does not work and I'll make a distribution for 8.6 as well.
